### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [EKrejci/prj-rev-bwfs-dasmoto#6]
https://github.com/EKrejci/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/resources/style.css#L14-L30

There is a lot of repetition occurring in these rules and there are opportunities for refactoring. Try to extract the common styles into a single rule with a more general selector, for example:

```css
.product h2 {
  color: white;
  font-weight: bold;
  font-size: 32px;
}

#frames {
  background-color: lightcoral;
}
```
